### ISSUE TITLE
Plugin fails on remote

### ISSUE THREAD

**Issue by Hipska** [mechatroner/vscode_rainbow_csv#128]
The plugin worked fine on remote vscode views, but recently doesn't work anymore.

I tried disabling and even reinstall of plugin.

This is shown in the runtime status after opening a csv file:

> - Cannot read properties of null (reading 'uri')
> - Cannot find module './rainbow_utils.js' Require stack:
>   - /xxx/vscode-server/extensions/mechatroner.rainbow-csv-3.5.0/extension.js
>   - /xxx/vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/loader.js
>   - /xxx/vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/bootstrap-amd.js
>   - /xxx/vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/bootstrap-fork.js
> - Cannot find module './rainbow_utils.js' Require stack:
>   - /xxx/vscode-server/extensions/mechatroner.rainbow-csv-3.5.0/extension.js
>   - /xxx/vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/loader.js
>   - /xxx/vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/bootstrap-amd.js
>   - /xxx/vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/bootstrap-fork.js

Is there anything else I can provide for troubleshooting?

**Comment by mechatroner** [comment]
Thanks for the bug report.
It also made me try to use remote vscode development for the first time!

Could you tell me, what type of remote development scenario do you have compared to the options here: https://code.visualstudio.com/docs/remote/remote-overview#_remote-tutorials ? Is it WSL development or remote or remote ssh or something else?
BTW I did some tests with a remote `code tunnel` server on a cloud ubuntu machine, and I couldn't reproduce the problem.
Please tell me more about your use-case, i.e. what commands are you running on the remote machine, are you using browser or vscode + the tunnel extensions? I also noticed 'vscode-server' in the stack trace, could it be that you are using 'vscode-server' command instead of `code tunnel` which seem to be a new recommended way of doing this?

**Comment by Hipska** [comment]
I'm using Remote-SSH indeed. It used to work before if I can remember it correctly.

The path is truncated, but actually this is where this extension puts the remote and temp files. It is in `.vscode-server` in the user directory.

I looked up the documentation and I don't think `code tunnel` is a way to go as the remote machine has no internet access.

**Comment by Hipska** [comment]
I removed some caches, reinstalled the plugin and restarted vscode again, and it seems everything is working again...
