### ISSUE TITLE
Separator confusion

### ISSUE THREAD

**Issue by KTW-NIRAS** [mechatroner/vscode_rainbow_csv#16]
If the header line is semicolon separated, and one or more lines contains text with commas, this error is displayed: 
WARN: Num of fields in Header and this line differs

**Comment by KTW-NIRAS** [comment]
It's when the file contains unescaped text. 
(I know this is bad practice, but I wanted to let you know)

Example:
```
ID;Name;Label;Description;Date
1;Test;Testing for errors, somewhere in this text;More text, and then some;22-08-2018
```
![rainbowcsv](https://user-images.githubusercontent.com/24385262/44444373-d0d7ec80-a5dc-11e8-8bdc-0b15fc27df2a.png)

**Comment by mechatroner** [comment]
I bet that the problem is that you are using "CSV" syntax while you should be using "CSV (semicolon)". Try changing it by clicking on "CSV" in lower right corner, like here: https://stackoverflow.com/questions/30775551/how-to-manually-set-language-for-syntax-highlighting-in-visual-studio-code/30776845#30776845

**Comment by KTW-NIRAS** [comment]
You are absolutely right, thanks! :-)
I didn't know about this feature.
