### ISSUE TITLE
Erroneously reports quoting error.

### ISSUE THREAD

**Issue by gregiare** [mechatroner/vscode_rainbow_csv#18]
In a csv file like the following;

Name,Number,Description
John Doe,="00000000000023456",Whatever

It says it has a quoting error and when hovering over the third column it reports it as the second column. It can't hand a preceding equals sign outside of the quotes. This is a common practice to prevent Excel from removing leading zeros.

**Comment by mechatroner** [comment]
Thanks for bug report,
I've never heard about this practice before, it is interesting to learn something new :)
One way to fix this is to alter tooltip logic: instead of showing an error on incorrect quoting it should fall back to simple double-quote agnostic csv dialect for the current field, like the syntax highlighting does. For more pedantic check there is still CSVLint which will catch and report the incorrectly quoted line.

**Comment by mechatroner** [comment]
I've altered the error handling logic in version 0.6.0: Instead of immediately failing on quoting error, the parser would try to recover from it using the same algorithm as the syntax highlighting. So now Rainbow CSV will correctly report header for the third column, but would still generate the parsing warning.
