### ISSUE TITLE
Add commands to select column for multi cursor editing

### ISSUE THREAD

**Issue by callamaris** [mechatroner/vscode_rainbow_csv#19]
Please add a command to select a column for multi cusror editing.

This would be usefull for multi cursor copy paste, adding/removing columns and in conjunction with other plugins (change case, align, sort etc.)

An option for selection with/without headers would be usefull too.

**Comment by mechatroner** [comment]
Hello!
Did you try RBQL feature which is a built-in SQL-like language?
Just run `RBQL` command to enter query-editing mode.
So, to emulate a copy-paste to specific column you can use something like:
`update a2 = a2 + ' test' where NR > 1`
NR > 1 here ensures that only non-header rows get modified.
To remove the second column you can use something like this:
`select a1, a3, a4` 
To add a column use:
`select a1, 'new column with const value', a3, a4`
To change case:
`update a2=a2.toUpperCase()`
To sort:
`select * order by parseInt(a1)`

SQL is a very simple language, to start you only need these keywords:
`select, update, where, order by, top, join`

**Comment by callamaris** [comment]
hi,
yes, i have tried RBQL and its a usefull tool to filter and edit data in a csv file.

But often i have to transform csv files partially or as a whole to something of a different file format (like funtion calls, cmd/bash files, config files etc.) or the other way around.

Most of the time i have some sort of script to do that for me, but thats not always the case. Sometimes i have to do this by hand.

In those cases i often use the multiline editing feature plus some plugins.

For this it would be handy, to have a command, that places multiline cursors in each cell of a csv column or that selects the values in a column for multiline editing.

**Comment by callamaris** [comment]
When each cell has the same amount of words, you can place multiline cursors at the beginning of each line and move the cursor with strg+arrow left/right. But this does not work, when the cells have a different number of words since strg+arrow keys does word wise naviagtion.

An alternative solution to my problem would be, to have a command with keybinding to navigate to the next/previous cells.

**Comment by mechatroner** [comment]
OK, I agree, this could be a very cool feature.
The problem is that I wasn't able to find a VSCode API function to add cursors. So we would need to create a request for VSCode team, and it can take a lot of time for them to implement.

BTW all of things you've described are possible with RBQL. e.g. to create a bash script which would rename files from old name in column1 to new name in column2:
`Select "mv " + a1 + " " + a2`
You can do something similar to generate multiple single line xmls, jsons, real sql queries, etc.
I also often do these kind of transformations.

And I am also planning to add column align command, so it might be helpful too.

**Comment by callamaris** [comment]
There is a new extension in the marketplace which helps with navigating multiple cursors:
[https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.better-cursors](https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.better-cursors)

You can not select the content of cells with different word count, but column navigation works fine with the commands _Move Cursors To Next/Previous_.

**Comment by mechatroner** [comment]
Turns out VSCode doesn't allow to create more than 10000 cursors simultaneously. So when user tries to modify bigger files, Rainbow CSV will show an error message.

**Comment by callamaris** [comment]
a limit of 10000 should be fine for most use-cases.

the error message avoids messing up larger  files by accident.

**Comment by mechatroner** [comment]
Good news: I've just published the updated version 0.6.0 with the new commands!
I've also added ColumnEditSelect command and instructions on how to remove a cursor from header line.
Bad news: I've found two problematic cases for multi-cursor editing approach.
1. Where should we put a cursor if we have a double-quoted field: inside our outside the double quotes? I've decided that for ColumnEditAfter/ColumnEditBefore it should be inside and for ColumnEditSelect it should be outside, but this solution doesn't look very elegant.
2.  Imagine a situation: User calls ColumnEditSelect, which selects a certain field in each line, then presses "Backspace" twice - first time to delete the field, second time to delete the separator. But this can lead to data corruption since some fields can be empty. So I've added a check that would not allow to call ColumnEditSelect if some fields are empty - this also looks ugly. Alternative solution is to select both field and separator with this command, so selection would never be empty, but it is also far from perfect.

**Comment by callamaris** [comment]
1. I would prefere to have the double quotes included in the selection, since they are not part of the line/column seperator. They behave more like escape characters (not exactly due to their location, but close enough) for the line/column seperators.

2. This is indeed an issue. I will do some testing in the next couple of days to see, if i can find a workable solution for this.

**Comment by mechatroner** [comment]
I've slightly changed the behavior to address problem 1: now ColumnEditBefore/After would fail if one of the multiple cursors is set to be placed within 2-character distance from a double quote. This should prevent accidental data-corruption scenario and is "compatible" with previous behavior.
