### ISSUE TITLE
Request a command to sample a short version from large file

### ISSUE THREAD

**Issue by neilsustc** [mechatroner/vscode_rainbow_csv#24]
Shall we have a command in the file explorer context menu which can read the first, for example, 100 lines from the `large.csv` file and then create a `large.top100.csv` in the same directory?

It will look a bit like this

![demo](https://image.ibb.co/bTQFDo/Preview_Csv_demo.gif)
(from [here](https://marketplace.visualstudio.com/items?itemName=yanxinwang.previewcsv))

**Comment by mechatroner** [comment]
Well, I would prefer just to include a link to "PreviewCSV" in README file to avoid functionality duplication. But the lack of public repository for "PreviewCSV" is really disappointing, because it can be improved with "tail" and maybe "random sample" commands. I think we should start by writing a Marketplace review with suggestion to create a public repo - as I understand this is the only way to reach the author.

**Comment by neilsustc** [comment]
I tried that extension but it didn't work... Since no repository is provided, I cannot fix it by myself.

And the fact is that, "PreviewCSV" actucally borrowed your "rainbow" functionality. So I feel we don't have to install two "same" extensions only for a small difference...

IMHO, it is just a small but sweet functionality, and easy to implement. I can make a PR if you agree to include it in your extension.

**Comment by mechatroner** [comment]
OK, go ahead, I will merge your PR

**Comment by mechatroner** [comment]
I've just published new functionality with version 0.8.0. 
Thank you very much!
