### ISSUE TITLE
Remove "Preview big CSV: head/tail" options in explorer when not relevant.

### ISSUE THREAD

**Issue by aNickzz** [mechatroner/vscode_rainbow_csv#32]
When right-clicking any file in the explorer the options for "Preview big CSV: head" and "Preview big CSV: tail" appear regardless of the item clicked (even if its a folder).

This should only appear if
* the file is a CSV
* the file is big

I'd also like to suggest adding an option to turn it off altogether. If you rarely open CSV's (like myself) these options are unnecessary clutter.

**Comment by mechatroner** [comment]
Hi @aNickzz, 
It's not possible to implement this feature the way you suggested because context menu can use only rudimentary logic to determine when to show specific entries. E.g. it is possible to determine file language, but it would be extension-based while many CSV files do not have .csv extension. Also AFAIK it is not possible to determine if file is big or not. Anyway, I've added two config options to disable these context menu entries, and by default only "Head" option is now ON.

**Comment by aNickzz** [comment]
I see, thank you for taking the time to do this, it's much appreciated :)
