### ISSUE TITLE
Columns 6, 7, and 9 appear to be the same colour

### ISSUE THREAD

**Issue by rorrison** [mechatroner/vscode_rainbow_csv#39]
I'm not sure if it's my setup, but it looks like columns 6 and 7 are the same colour in a 7 or 8 column file, and 9 is the same colour again in a 9 or 10 column file.  I haven't checked beyond that.

I realize that colours will need to be repeated, but it should be possible to have more distinction between nearby columns.

![Capture](https://user-images.githubusercontent.com/5174179/61632795-990e7480-ac85-11e9-8531-2d43fd9ab89d.PNG)

**Comment by mechatroner** [comment]
Hi @rorrison, the colors depend on the colorscheme that you are using. Looks like your colorscheme is using one single color for "variable.parameter", "variable.numeric" and "markup.bold" tokens. I tried to opmitize the set of tokens so that the colors would be different in the default VSCode colorscheme. You can actually adjust Rainbow CSV colors while keeping your current color scheme for all other file types, just follow the steps described in the readme file: https://github.com/mechatroner/vscode_rainbow_csv/blob/master/test/color_customization_example.md#colors-customization

**Comment by rcoundon** [comment]
> Hi @rorrison, the colors depend on the colorscheme that you are using. Looks like your colorscheme is using one single color for "variable.parameter", "variable.numeric" and "markup.bold" tokens. I tried to opmitize the set of tokens so that the colors would be different in the default VSCode colorscheme. You can actually adjust Rainbow CSV colors while keeping your current color scheme for all other file types, just follow the steps described in the readme file: https://github.com/mechatroner/vscode_rainbow_csv/blob/master/test/color_customization_example.md#colors-customization

Thanks, This solved the issue for me
