### ISSUE TITLE
Off button

### ISSUE THREAD

**Issue by Blurp-06** [mechatroner/vscode_rainbow_csv#49]
Dear developers of vscode rainbow csv,

under the file you have a button called turn rainbow csv off.
but if it is off i cant find the on button.
please help.

**Comment by mechatroner** [comment]
Hi @Blurp-06 ,
You can turn the highlighting back on by either:
1. Clicking language button in the lower right corner of your editor and choosing the appropriate rainbow syntax (see the table in plugin description)
2. Selecting the separator character with mouse cursor -> right click -> "Set as Rainbow separator"

I didn't add the "Rainbow On" button because the "Rainbow Off" was supposed to be used when Rainbow CSV incorrectly detected non-csv file as csv and the user would want to completely disable Rainbow CSV for that file, leaving "Rainbow On" button could be a little annoying.

**Comment by dnut** [comment]
I clicked "Rainbow OFF" instinctively because I thought it was a toggle that was indicating the current state to be off. The word OFF being in all caps had me convinced it was a status indicator. I would have been less confused if it said "Turn off Rainbow".

**Comment by igor9silva** [comment]
Just giving a feedback, I've been through the same (accidentally tapping turn off rainbow) and had to get here to find the solution.

**Comment by ainou** [comment]
I have to agree with dnut, the same happend to me. I was able to "re-enable" by going with option 2 above.
Thanks love the extension.

**Comment by elbrandt** [comment]
Once 'Rainbow OFF' is clicked, is that stored somewhere? If I close and re-open the file, it is not detected as Rainbow. I can select a comma and choose 'Set as Rainbow Separator' and the file will be rainbow'ed until I close and re-open it again, and then it still won't be automatically rainbowed. How do I 'unflag' a file as being 'Rainbow OFF'?

**Comment by mechatroner** [comment]
Thanks for the bug report, @elbrandt. I will make sure to fix this in the next release.

**Comment by mechatroner** [comment]
Actually, it might be better to solve this problem in coordination with VSCode team, I just opened a ticket there: microsoft/vscode#136263

**Comment by ToontjeM** [comment]
+1 here. Ran into the same problem. It's very intuitive to switch Rainbow off, have to Google and end up here on how to switch it back on.

**Comment by mechatroner** [comment]
Since there was a lot of feedback regarding this issue, I added the "Rainbow On" button with version 3.8.0. Thanks, everyone!
