### ISSUE TITLE
Associate with .TAB files

### ISSUE THREAD

**Issue by polytrophic** [mechatroner/vscode_rainbow_csv#5]
TAB is an accepted and widely used file extension in place of TSV

(In fact, in MS Access, if you try to ingest a .TSV, it will tell you that it only supports .TAB files)

Would you please add a file association for your sweet extension for .TAB as well?

Thank you!

**Comment by mechatroner** [comment]
Thanks! I will probably include this feature in the next release. Turns out .tab extension is also mentioned in  Wikipedia along with .tsv: https://en.wikipedia.org/wiki/Tab-separated_values 
The only things that bothers me is that .tab extension is also used for guitar tabulatures: https://en.wikipedia.org/wiki/ASCII_tab
Anyway this is only a temporal measure: sooner or later, after VS Code has the language changing API, we will be able to run content-based autodetection and file extension will become irrelevant.

**Comment by polytrophic** [comment]
Ah, thank you for taking the time even if it's temporary! Your plugin has saved me much frustration. Very much appreciated.

**Comment by mechatroner** [comment]
Published with version 0.2.1
