### ISSUE TITLE
Usage of Autodetect_separators

### ISSUE THREAD

**Issue by clarotech** [mechatroner/vscode_rainbow_csv#51]
Hi - I have been using the extension for a while and it is excellent.

I now have a file that has "¦" as the separator. I have added this to the Autodetect_separators list but this seems to have no effect.

Have I misunderstood what this setting is for - can you set your own separator characters here?

**Comment by mechatroner** [comment]
Thank you for the feedback!
Currently Rainbow CSV supports only those separators which are listed in this table: https://github.com/mechatroner/vscode_rainbow_csv#supported-separators

I am planning to add support for other separators including unicode separators like "¦" and multi-character separators. The problem here is that VSCode currently doesn't have an API to dynamically generate new grammars so I will have to work with editor development team to support this. The main ticket for this is: https://github.com/mechatroner/vscode_rainbow_csv/issues/1
