### ISSUE TITLE
export data to excel

### ISSUE THREAD

**Issue by heartacker** [mechatroner/vscode_rainbow_csv#53]
hi, It would be nice if we could export csv、tsv、data to excel. 3q：D

**Comment by mechatroner** [comment]
Yeah, this could be cool, but I suspect that adding this feature would increase the codebase size 10 times or more. 2 minutes googling and I couldn't find any JavaScript library that could save an array of JS objects/arrays as an xlsx file. Also as I understand the main point of Excel (I am not an experienced Excel user at all) is that Excel cells are typed, so in order to properly convert to Excel user would have to specify data types of the columns - this could be very time consuming. While we would save user some time on specifying the delimiter, they would still have to do most of the work.
Please correct me if I am wrong on something.

**Comment by heartacker** [comment]
Oh, I'm not familiar with JS/TS,
and there is an JS package FYI: https://github.com/exceljs/exceljs#writing-xlsx
anyways,thx

**Comment by mechatroner** [comment]
Let's keep this ticket open, but I am not sure if there is a way to reasonably implement this feature. "exceljs" looks huge, and I will only consider a dependency-free library that would not significantly increase the codebase size (perhaps it is possible to extract only basic xlsx-saving functionality from exceljs, I don't know). And we still haven't decided how to deal with string->datatype conversion, should we just guess it when possible and suggest the user to modify autodetected types during the export? Maybe it is better to implement Excel export as a separate VSCode extension, in that case we could just mention it in the README file as a good integration solution.

**Comment by RandomFractals** [comment]
hi guys, just so you know my data preview extension has save as xlsx option & a few more ;)

Please see release notes on that feature addition here:

https://github.com/RandomFractals/vscode-data-preview/releases/tag/v1.28.0

**Comment by mechatroner** [comment]
Thank you, @RandomFractals ! I think that's exactly what we needed. I updated the README file and added references to the related extensions including Data Preview.

**Comment by RandomFractals** [comment]
hey @mechatroner thanks for doing that.

Can you remove Parquet part? I have not added that yet. 

Maybe, mention Arrow or Avro instead. Those are supported by my extension.

I'll add your extension to my recommended extensions list here as well, so devs can find relevant ext's easily:

https://github.com/RandomFractals/vscode-data-preview#recommended-vscode-extensions
