### ISSUE TITLE
Support for multiple headers

### ISSUE THREAD

**Issue by jeffwarnica** [mechatroner/vscode_rainbow_csv#56]
I have a CSV file that has two rows of headers.
(gnuplot can figure this out automatically).

If not automatically, I should be able to note two (or N) rows as headers, especially for the query part.

**Comment by mechatroner** [comment]
Hi @jeffwarnica,
What do you mean two rows of headers? I never heard of CSV files with multiple headers before. Is this just two csv files concatenated into one file like this:
```
name, age
Joe, 20
Bob, 30
.....
City,Country,Population
Moscow,Russia,12000000
London,UK,10000000
....
```
Or something entirely different?

**Comment by jeffwarnica** [comment]
https://novascotia.ca/coronavirus/data/COVID-19-data.csv is an example (I grant it shouldn't exist, but it does)
**g**
Reporting,New,Total,Total cases,Currently hospitalized,,New,Cumulative Case Numbers by Zone,,,,Gender %,,Age Demographics %,,,
Date,Cases,Negative,Recovered,non-ICU,ICU,Deaths,Western,Northern,Eastern,Central,Female,Male,0 -> 19,20 -> 44,45 -> 64,65+
2020-03-15,3,415,0,,,0,,,,,,,,,,
2020-03-16,2,671,0,,,0,,,,,,,,,,
2020-03-17,2,934,0,,,0,,,,,,,,,,
2020-03-18,5,1141,0,,,0,,,,,,,,,,
2020-03-19,2,1373,0,,,0,,,,,,,,,,

**Comment by mechatroner** [comment]
Thanks, I got it, basically the second header can be used as a subdivision for the value in the first header, like different ranges for "Age Demographics %" to avoid repeating "Age Demographics %" multiple times. 
So, My opinion is that even if it would be able to use the two first rows in such notations as headers for RBQL queries, it would be extremely confusing for the users what column names should be used. E.g. is it "Age Demographics %" or "Age Demographics % 0-19" or just "0 -> 19"? So I don't want to add multi-header support because this is a very uncommon notation, it is hard to implement and maintain, and it is not clear how to represent this feature in the UI.
From the other hand if you just want to skip the two header rows in RBQL query you can already do this by adding `... WHERE NR > 2 ...` to your query. Also In case when you really want to use values from the second row as header names, I am planning to support virtual headers in RBQL. Currently you can use virtual headers for column hover info, but it should be possible to use them in RBQL queries too - I will add this feature at some point. So I think that combination of `... WHERE NR > k ...` trick and virtual headers in queries should cover most of the use cases.
