### ISSUE TITLE
Add a "virtual" align

### ISSUE THREAD

**Issue by mirije** [mechatroner/vscode_rainbow_csv#62]
An option to only display the aligned version without actually modifying the file would be great. 
If this "virtual align" is on, the file could be displayed aligned but if you don't manually change any data it would not trigger the "do you want to save the changes" dialog after closing.
I'm not sure what should happen with alignment whitespace if you modify the file manually.

**Comment by mechatroner** [comment]
Hi @mirije , 
I like your idea, but I don't think there is a way to do it using current VSCode API/features. If VSCode would support read-only mode ( microsoft/vscode#4873 ) then it would be possible to create a new temporary aligned version of the file and open it in read-only mode. This would also solve the problem with modification since it would be explicitly disallowed by the read-only mode. Another option is to open the aligned version in a webview - but this will essentially duplicate the functionality of existing extensions: https://marketplace.visualstudio.com/items?itemName=janisdd.vscode-edit-csv and https://marketplace.visualstudio.com/items?itemName=GrapeCity.gc-excelviewer so I don't think it's worth doing. So when/if the read-only mode is supported I will think about implementing read-only align feature. I will keep the issue open, but we don't have a way to implement this currently.

**Comment by mechatroner** [comment]
I added `align_in_scratch_file` config option in version 3.7.0. This might not be exactly a "virtual" align which is not supported by the current API, but still, it keeps the original file unchanged.
