### ISSUE TITLE
Alignment weird when encountering Chinese characters

### ISSUE THREAD

**Issue by github-young** [mechatroner/vscode_rainbow_csv#69]
I find that the alignment of commas is not correct when processing csv files containing Chinese characters, as shown in the figure below:
![rainbowCSV1](https://user-images.githubusercontent.com/19162282/91147225-8cf7b080-e6ea-11ea-830a-1ffa27a6031b.png)
What I expect is like the figure below (I manually align it, but indeed it cannot be aligned perfectly):
![图片](https://user-images.githubusercontent.com/19162282/91147654-21621300-e6eb-11ea-87ce-1331beb7dc05.png)

The following is the original text in case you need it.
```
编号 ,配件     ,型号                   ,数量   ,渠道   ,￥      ,状态
1    ,主板     ,微星B450m mortar max   ,1     ,二手   ,284.5   ,已买
2    ,CPU      ,AMD 3600(带原装散热)   ,1     ,二手   ,674.5   ,已买
3    ,显卡     ,AMD HD7870             ,1    ,二手    ,200     ,-
4    ,内存     ,Crucial 8Gx2 3200 MHz  ,1    ,京东    ,399     ,已买
5    ,固态     ,SN550 1T               ,1    ,淘宝    ,719     ,已买
6    ,电源     ,酷冷GX450              ,1    ,京东    ,269     ,已买
7    ,风扇     ,先马12cm黑框红叶        ,3    ,淘宝    ,27      ,已买
8    ,机箱     ,酷冷大师Q300L           ,1    ,二手   ,135     ,已买
```

**Comment by mechatroner** [comment]
Hi @github-young ,
Thank you for bringing up this interesting problem!
I didn't thoroughly analyze this issue yet, but it looks that the default VSCode font ("Consolas, 'Courier New', monospace") allocates two times more space for Chinese characters. So it could be possible to adjust the alignment logic based on the character values. But this wouldn't guarantee proper alignment for users who use non-default fonts in VSCode. I am not an expert in fonts so any suggestions on how we can fix this in a reliable way without making the problem worse would be much appreciated. 

Adding some relevant links as a starting point for the discussion:
https://stackoverflow.com/questions/50421855/how-can-i-line-up-english-and-chinese-characters-of-a-monospace-font-for-css
https://graphicdesign.stackexchange.com/questions/113534/monospace-font-that-supports-both-english-and-japanese
https://groups.google.com/g/chinesemac/c/1haGW9aKHis?pli=1

**Comment by yoyoys** [comment]
just some reference:
- CJKV fonts are all 2 spaces width.
- some useful article there [stackoverflow](https://stackoverflow.com/questions/21109011/javascript-unicode-string-chinese-character-but-no-punctuation)
- [CJKV](https://en.wiktionary.org/wiki/CJKV)

If I have time I will try fix this.

**Comment by ja-jp-utf8** [comment]
Hi @mechatroner,

I am trying to fix this issue.
But, "unicode grapheme cluster" is too difficult for me.
In particular, emoji with "zero width joiner" is too difficult.

So, I used npm library "graphemesplit".

https://github.com/ja-jp-utf8/vscode_rainbow_csv/tree/support_align_with_cjkv

It works to adjust with correct alignment in Japanese.

If you like this fix, I will create pull request.

**Comment by mechatroner** [comment]
Hi @ja-jp-utf8, that's really cool! 
I see you did a lot of research to implement this, thank you!

Here are some of my thoughts on this:
1. I usually prefer not to add additional dependencies when it is not absolutely necessary, but I am feel kinda OK towards "graphemesplit" - the dependency tree is not very high, looks like it has only few transitive dependencies, all of them seems to be professional projects that require deep unicode knowledge. So this is not an issue - just a comment on your selection of graphemesplit.
2. We need an integration test, "rainbow_csv" has already a couple of them, so we need another one to at least have some minimal assurance that the new alignment algorithm works correctly - I need a test CSV file or couple of files with lots of wide characters and some emojis since as you say they represent significant challenge for the alligners.
3. This is a question - when you test your algorithms on some random files, do the vertical allignment lines look completely vertical or there is still some minor wobbling? 
4. Do I understand correctly that the main reason we need to add the "graphemesplit" lilbrary is emojis allignment and otherwise you can write a standalone alignment module? If this is the case I would argue that this is kinda not a big deal. Properly aligning "normal" wide logograms is already a huge improvement over the current situation. So if you can write a standalone aligner that would properly align normal "wide" characters but would work incorrectly in some corner cases such as emojis, I would strongly prefer to use this home-made solution. But we still would need a CSV integration test file with these emojis just to show where the new aligner does a non-ideal job and where it works reasonably well (see item 2)
5. What about performance? I need some metrics to compare how much longer it now takes to allign a 300K lines file - this is about the biggest file that VSCode can support. BTW this will also slow down alignment for files that have only ascii characters in them and I would argue that this is a significant proportion of CSV files. If the time difference is significant we can try to come up with some optimizations - e.g. start with optimistic aligning but if at some point we encounter a wide character ( which should be fairly early in majority of CSV files that have wide characters ), restart the whole alignment process using the different algorithm.

So, as you see, I just can't merge the new code without a new integration test and some performance measurements from you.
And if you are saying that we can do without the library in cases when we don't have emojis - I say let's just ignore this case for now and roll out our own custom aligner that will work in other 95% cases with "normal" wide chars.

**Comment by AntoineGlacet** [comment]
Hi,
I faced the same problem with Japanese characters, sorry that I cannot contribute to a solution but it would be very appreciated if there was a solution/workaround.

**Comment by mechatroner** [comment]
Update: Alignment for double-width characters should work starting from version 3.6.0. It is controlled by `rainbow_csv.double_width_alignment` which is `true` by default. The new algorithm is based on a slightly modified version of wcwidth library: https://github.com/timoxley/wcwidth which I really like because it is straightforward and minimalistic. I tested it with Chinese characters and emojis and it works as expected.

The only issue is that although the alignment is much better now, it might still be a little "wobbly" (or not, depending on your environment) which is likely caused by font rendering: https://stackoverflow.com/a/7221188/2898283.
In my environment (Windows) I found that setting `"editor.fontFamily": "'MS Gothic', monospace"` makes alignment absolutely straight and completely eliminates wobbling, but "MS Gothic" font family significantly decreases text readability in my opinion, so I can't recommend using it even for csv-files only. 
I would really appreciate it if someone could recommend a better alternative to "MS Gothic" - we can then add it to the README file as a recommended workaround.
