### ISSUE TITLE
Support RBQL

### ISSUE THREAD

**Issue by alexrussell** [mechatroner/vscode_rainbow_csv#9]
First off I must admit that I don't have to open CSV files that often, but when I do, this plugin really helps, so thank you very *very* much for putting it together (and porting it from the vim version).

One thing that I think would be great is if you could also port the RBQL stuff over too. I'm aware that the RBQL parser is written in Python, so presumably this would require porting it to JS, which is probably more time-constrained than difficulty/practicality-constrained. Also, the way that the plugin does the filtering in the cases of SELECT would need to be considered.

It probably wouldn't be a great idea to literally filter the lines of the CSV out that don't match the SELECT, as that would go against the user expectation of a text buffer containing the whole file (even if, yes, they are the ones who filtered the CSV in the first place!). You could maybe use code folding cleverly to do the filtering, but that may well end up with a lot of fold marks everywhere, plus the fact that they can easily be accidentally unfolded by the user.

So what I'd probably suggest is having a separate view entirely (activated by a command would be fine) for RBQL mode that has a box for the RBQL expression at the top (like the settings in VSCode has) which is automatically parsed and executed (if valid RBQL) and the results shown below the bar. That way, it's not a text buffer per se (though if you could somehow keep the syntax highlighting and ability to edit lines that'd be even more amazing), but still feel VSCode-y. In fact, looking at the way that (now old - I see I have a new "experimental settings" page!) VSCode settings page works, if you could mimic that as much as makes sense, that'd be best probably.

**Comment by mechatroner** [comment]
Hello!
Thanks for the feedback!
I've actually just finished integration with RBQL (see the bottom of updated README.md), although I haven't much tested it yet. At the first stage I plan to release it in "Experimental" mode primarily because I've cut the corner and didn't port it to JS, so in order to run in JS mode both Python and Node.JS interpreters are required, which is pretty lame. 
I am not sure if it is possible to use the same mechanism as VSCode settings: as an extension "Rainbow CSV" is limited by API functions that VSCode provides. So I found only two options for SELECT query input: "Input Box" and html preview. I've decided to support both since each of them has their own pros and cons.
I plan to release the new version soon, but if you want to help you can manually download and install the extension to test the new features.

**Comment by alexrussell** [comment]
Haha how weird that I thought of it at approximately the same time you were finishing off initial support!

I'll try to check it out, thanks.

**Comment by mechatroner** [comment]
In production
